# Generated by Django 3.1.5 on 2021-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('dateLivraison', models.DateTimeField()),
                ('menu', models.CharField(max_length=256)),
            ],
        ),
    ]
