# Generated by Django 3.1.5 on 2021-02-18 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_commands_datecommandepasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='numTel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 16, 7, 33, 157512)),
        ),
    ]
