# Generated by Django 3.1.5 on 2021-02-18 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 16, 8, 3, 249872)),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateLivraison',
            field=models.DateTimeField(null=True),
        ),
    ]
