# Generated by Django 3.1.5 on 2021-02-18 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='livree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 19, 39, 19, 18411)),
        ),
    ]
