# Generated by Django 3.1.5 on 2021-02-19 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210218_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='link',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 19, 1, 11, 5, 548067)),
        ),
    ]
