# Generated by Django 3.1.5 on 2021-02-22 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210222_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 11, 18, 14, 774194)),
        ),
        migrations.AlterField(
            model_name='pole',
            name='LienFb',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pole',
            name='LienInsta',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
