# Generated by Django 3.1.5 on 2021-02-22 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210222_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 11, 53, 22, 806356)),
        ),
        migrations.AlterField(
            model_name='pole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/poles'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/poles'),
        ),
    ]
