# Generated by Django 3.1.5 on 2021-02-26 17:45

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210222_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='rang',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 26, 18, 45, 49, 957688)),
        ),
        migrations.AlterField(
            model_name='pole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_path),
        ),
        migrations.AlterField(
            model_name='pole',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_path),
        ),
    ]
