# Generated by Django 3.1.5 on 2021-02-26 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210226_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 26, 18, 52, 14, 556277)),
        ),
        migrations.AlterField(
            model_name='pole',
            name='rang',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
    ]
