# Generated by Django 3.1.5 on 2021-03-03 15:06

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210228_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeriepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legende', models.CharField(blank=True, max_length=64, null=True)),
                ('texte', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=main.models.upload_path)),
                ('dateUpload', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 16, 6, 37, 727433))),
            ],
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 16, 6, 37, 726403)),
        ),
    ]
