# Generated by Django 3.1.5 on 2021-03-03 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210303_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriepic',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 16, 14, 10, 155444)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 16, 14, 10, 156468)),
        ),
    ]
