# Generated by Django 3.1.5 on 2021-03-11 17:19

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210303_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shotgun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('dateShotgun', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 18, 19, 40, 134468))),
            ],
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 18, 19, 40, 132467)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 18, 19, 40, 134468)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_path_galerie),
        ),
    ]
