# Generated by Django 3.1.5 on 2021-03-12 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210311_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotgunConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=512)),
                ('nbPlace', models.IntegerField(blank=True)),
                ('dateDebut', models.DateTimeField(null=True)),
                ('dateFin', models.DateTimeField(null=True)),
                ('dateCrea', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 19, 50, 649979))),
            ],
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 19, 50, 645958)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 19, 50, 647984)),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='dateShotgun',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 19, 50, 648985)),
        ),
    ]
