# Generated by Django 3.1.5 on 2021-03-28 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210328_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqrcode',
            name='gagnant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 18, 36, 43, 295624)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 18, 36, 43, 296621)),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='dateShotgun',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 18, 36, 43, 296621)),
        ),
        migrations.AlterField(
            model_name='shotgunconfig',
            name='dateCrea',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 18, 36, 43, 297618)),
        ),
    ]
