# Generated by Django 3.1.5 on 2021-04-19 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210419_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='resultat',
        ),
        migrations.AddField(
            model_name='match',
            name='resultatEquipe1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='resultatEquipe2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 17, 45, 54, 99592)),
        ),
        migrations.AlterField(
            model_name='eventqrcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 17, 45, 54, 106610)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 17, 45, 54, 102587)),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='dateProno',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 17, 45, 54, 108607)),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='dateShotgun',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 17, 45, 54, 103617)),
        ),
        migrations.AlterField(
            model_name='shotgunconfig',
            name='dateCrea',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 17, 45, 54, 104726)),
        ),
    ]
