# Generated by Django 3.1.5 on 2021-04-19 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210419_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 22, 58, 10, 205132)),
        ),
        migrations.AlterField(
            model_name='eventqrcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 22, 58, 10, 209118)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 22, 58, 10, 207124)),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='consentement',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='dateProno',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 22, 58, 10, 211184)),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.match'),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='dateShotgun',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 22, 58, 10, 208225)),
        ),
        migrations.AlterField(
            model_name='shotgunconfig',
            name='dateCrea',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 22, 58, 10, 208225)),
        ),
    ]
