# Generated by Django 3.1.5 on 2021-05-02 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210422_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='campagneCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('dateLivraison', models.DateTimeField(null=True)),
                ('menu', models.CharField(max_length=256)),
                ('dateCommandePasse', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 18, 13, 42, 727846))),
                ('numTel', models.IntegerField(null=True)),
                ('livree', models.BooleanField(blank=True, default=False, null=True)),
                ('link', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 18, 13, 42, 716959)),
        ),
        migrations.AlterField(
            model_name='eventqrcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 18, 13, 42, 723804)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 18, 13, 42, 719998)),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='dateProno',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 13, 42, 726846)),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='dateShotgun',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 18, 13, 42, 721469)),
        ),
        migrations.AlterField(
            model_name='shotgunconfig',
            name='dateCrea',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 18, 13, 42, 722876)),
        ),
    ]
