# Generated by Django 3.1.5 on 2021-05-03 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210503_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagnecommande',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 7, 48, 50, 587914)),
        ),
        migrations.AlterField(
            model_name='campagnecommande',
            name='demande',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='commands',
            name='dateCommandePasse',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 7, 48, 50, 583921)),
        ),
        migrations.AlterField(
            model_name='eventqrcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 7, 48, 50, 586879)),
        ),
        migrations.AlterField(
            model_name='galeriepic',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 7, 48, 50, 585913)),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='dateProno',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 7, 48, 50, 587914)),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='dateShotgun',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 7, 48, 50, 585913)),
        ),
        migrations.AlterField(
            model_name='shotgunconfig',
            name='dateCrea',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 7, 48, 50, 586879)),
        ),
    ]
